version: '3.7'

services:
  node-app:
    build: ./node
    ports:
      - 3000:3000

  python-app:
    build: ./python
    ports:
      - 4000:4000

  springboot-app:
    build: ./springboot
    ports:
     - 8080:8080


